# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lak453.github.io
date_format: "ordinal"
title: Howard Blog
subtitle: "Ho Wang Ho(Howard)"
description: "Zhuang Ma's personal blog, WeChat Official Account: Introverted Programmer"
keywords: Howard Blog,Programmer,C++
timezone: Asia/Hong Kong
encoding: "utf-8"
# The year displayed at the bottom left of the page
since: 2015
# Source code repository, please replace with your own
repository: lak453/lak453.github.io
# CDN acceleration configuration for css and js resources
cdn:
    jsdelivr:
        enabled: false
# Optional component configuration
components:
    # Share
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # Busuanzi visitor statistics
    busuanzi:
        enabled: false
        start_date: 2024-06-16
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # Article word count
    word_count:
        enabled: true
    # QR code at the top right of the page and on the "About" page
    # To change the image, please replace assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: Introverted Programmer
 # Which view to use for the wiki index page, supports list/cate
    wiki:
        view: cate
    # Image lightbox effect feature
    fancybox:
        enabled: false
# Compress page content
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# Code highlighting style, for supported theme list see https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Ho Wang Ho (Howard)
organization: 
organization_url: 
github_username: Lak453
location: Hong Kong
email: hoho@msu.edu

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Categories

  -
    href: /archives/
    label: Archives
    mobile-hidden: true

  -
    href: /open-source/
    label: Open Source
    mobile-hidden: true

  -
    href: /Resume/
    label: Resume

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links
    mobile-hidden: true

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
    banner:
        # Home page banner area text color
        color: "#fff"
        # Home page navigation bar text color
        nav-color: "rgba(255, 255, 255, .5)"
        # Home page banner area background color
        background-color: "#4183c4"
        # Home page banner area background image
        # background-image: "/assets/images/octicons-bg.png"
        # background-repeat: "no-repeat"
        # background-size: "cover"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # Whether to support full-text search
    fulltext: false
    # Maximum number of search results to display
    limit: 3

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false